### PR TITLE
Google Maps Distance API

### LINKED ISSUE #33: Query Google Maps API to calculate driving/cycling/walking distance and time between points

### PR DESCRIPTION
**Pull request by jaschn**
closes #33

### CODE REVIEW

**Comment by johannesmols** [comment]
Hi @jaschn, looks really good. I merged your code.
How can I use it though? I can see the GetDistanceAndTime method returns null, and the CalculateDistances method is void.

**Comment by jaschn** [comment]
Hi @johannesmols, with CalculateDistance the points between which the distance should be calculated are specified. All possible combinations of origins and destiantions are calculated. When this is finished a single result can be accessed via GetDistanceAndTime.
I could maybe add that it takes a complete graph as input and then single distances can be accessed.

**Comment by jaschn** [comment]
Okay i found one more bug and not all calculated Route were added.

**Comment by jaschn** [comment]
I fixed the bug and pushed the commit to the branch.

Simple Example
```
        var origins = new List<LatLng>() { new LatLng(55.930385, -3.118425), new LatLng(50.187692, 14.421150) };
        var destinations = new List<LatLng>() { new LatLng(55.950385, -3.118425), new LatLng(50.087692, 14.521150) };
        await GoogleMapsDistance.CalculateDistances(TravelMode.Driving, origins, destinations);

        var distance = await GoogleMapsDistance.GetDistanceAndTime(TravelMode.Driving, origins.ElementAt(0), destinations.ElementAt(1));
        result = distance.distance.ToString();
```

I can adapt the functionality to make the use in the Simulation easier.

**Comment by johannesmols** [comment]
Thank you, I will check it out later :)

**Comment by johannesmols** [comment]
Hi @jaschn, it's working with the example. So why do you put in multiple coordinates for origin/destination? Does it then calculate the distance between all of them or how does it work? I would expect to have a function where i put in an origin and destination and then get the distance/time returned. That would be nice if it is possible to return it instead of having to know at what indices the result I'm looking for is. Would make it easier to use in the simulation.

**Comment by jaschn** [comment]
With the Google Maps Distance Matrix API you can put multiple origins and destinations (25 max for each) in an API call at the same time. It the calculates the distance from each origin to all destinations, creating a matrix. I don't want to make an API call for each single distance calculated to reduce the amount of calls.
You don't need any index to access the result, maybe the example is a little bit unclear. The result function is called just with origin and destination coordinates. These just have to been previously calculated via the CalculateDistances Method. Currently origin and destination can't be interchanged.
`var distance = await GoogleMapsDistance.GetDistanceAndTime(TravelMode.Driving, new LatLng(55.930385, -3.118425), new LatLng(50.087692, 14.521150));`

**Comment by johannesmols** [comment]
Ahh okay that makes a lot of sense with the API call. Then I misunderstood how it is stored. That's easy enough to retrieve then. I will incorporate it in the simulation :)

**Pull request merged**
